# Generated by Django 5.0.7 on 2024-09-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('hobbies', models.TextField()),
                ('soft_skills', models.TextField()),
                ('languages', models.TextField()),
                ('references', models.TextField()),
                ('education', models.TextField()),
                ('work_experience', models.TextField()),
                ('photo', models.ImageField(upload_to='profile_photos/')),
            ],
        ),
    ]
